[workspace]
resolver = "2"
members = [
  "specs",
  "scrub",
  "pusher",
  "transcribe",
  "s3",
  "markdown",
  "optimizer",
  "cleaner",
  "pipeline",
]

[workspace.package]
name = kerust
version = "0.1.0"
edition = "2021"
rust-version = "1.91.0"
authors = ["haikal ariff"]
repository = "https://github.com/haikalariffhalim/kerust"
license = "MIT"
description = "A parser and compiler written in Rust. Currently, it has support for some of the language."
