[package]
name = "pipe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
scrub = { path = "../scrub" }
pusher = { path = "../pusher" }
s3 = { path = "../s3" }
comp = { path = "../comp" }
md = { path = "../md" }
pipeline= { path = "../pipeline" }
specs = { path = "../specs" }
